content:
  - changed-files:
      - any-glob-to-any-file: ['content/**']

documentation:
  - changed-files:
      - any-glob-to-any-file: ['**/*.md', 'docs/**']

ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/**', 'lighthouserc.json']

frontend:
  - changed-files:
      - any-glob-to-any-file: ['src/**']

tooling:
  - changed-files:
      - any-glob-to-any-file:
          ['scripts/**', 'package.json', 'tsconfig.json', 'vite.config.ts', 'eslint.config.js']

tests:
  - changed-files:
      - any-glob-to-any-file: ['tests/**']
